### ISSUE TITLE
Simplify nested anonymous classes, when creating instance of them

### ISSUE THREAD

**Issue by T-256** [ynkdir/py-win32more#14]
I have this line in C program:
```c
const VARIANT VARIANT_VAL = { {{VT_NULL, 0}} };
```

Converted to `pywin32-more`:

```py
from win32more.Windows.Win32.System.Variant import VARIANT, VT_NULL

VARIANT_VAL = VARIANT(VARIANT._Anonymous_e__Union(VARIANT._Anonymous_e__Union._Anonymous_e__Struct(VT_NULL, 0)))
```

Could it be smaller?
For example:
```py
# Auto Converts Tuple to calling argument types classes if they are Struct or Union.
VARIANT_VAL = VARIANT( ( (VT_NULL, 0), ) )
```

**Comment by ynkdir** [comment]
`VARIANT( ( (VT_NULL, 0), ) )` will work.
I think it is good way.
I would rather prefer `VARIANT(vt=VT_NULL)`.

**Comment by T-256** [comment]
> `VARIANT( ( (VT_NULL, 0), ) )` will work.

:) Yes, Works


> I would rather prefer `VARIANT(vt=VT_NULL)`.

Nice!
