### ISSUE TITLE
[Feature Request] binding generate for apis

### ISSUE THREAD

**Issue by T-256** [ynkdir/py-win32more#20]
Similar to [windows-bindgen](https://kennykerr.ca/rust-getting-started/standalone-code-generation.html) Rust crate, it would generate only given names:
Example:
- `export.txt` (potentially generated with [print-used](https://github.com/ynkdir/py-win32more/issues/16#issuecomment-1763257872)):
```txt
win32more.Windows.Win32.Foundation.BOOL
```
- then pass it to generator:
```
generate.py file.win32.json export.txt
```
- it will create `win32out.py` with this:
```py
from __future__ import annotations
from ctypes import POINTER
from win32more import ARCH, Boolean, Byte, Bytes, Char, ComPtr, Double, EasyCastStructure, EasyCastUnion, FAILED, Guid, Int16, Int32, Int64, IntPtr, MissingType, SByte, SUCCEEDED, Single, String, UInt16, UInt32, UInt64, UIntPtr, Void, VoidPtr, cfunctype, cfunctype_pointer, commethod, winfunctype, winfunctype_pointer, make_ready

BOOL = Int32

make_ready(__name__)
```

Then it can used via `from win32out import BOOL`.

Advantage here is only dependency is `win32more/__init__.py` file and no more need `win32more/Windows/*`

**Comment by ynkdir** [comment]
Did you try generator.py `-s selector.txt` `-o out.py`?

Unfortunately -o is broken now.

**Comment by T-256** [comment]
Yes, I'm aware of that, Currently working on them: https://github.com/T-256/py-win32more/tree/onefile
