### ISSUE TITLE
 Proposal: Project CreateInstance method into constructors

### ISSUE THREAD

**Issue by sotanakamura** [ynkdir/py-win32more#30]
`CreateInstance` method create instance, for example;

```py
window = Window.CreateInstance(None, None)
``` 

It should be more natural like

```py
window = Window()
```

**Comment by ynkdir** [comment]
Added via 3bbe37ae3383e02cd52e302103a82582b07cb5a1

**Comment by ynkdir** [comment]
Reverted.

`__init__` is also called from ctypes when the class is used as parameter of callback function.

```python
class A(c_void_p):
    def __init__(self):
        pass

@WINFUNCTYPE(void, A)
def callback(obj):
    ...
```
