### ISSUE TITLE
DEBUG: missing type 'Guid' and Guid struct not generated for related functions

### ISSUE THREAD

**Issue by fgimian** [ynkdir/py-win32more#37]
Hey there, when using a `selector.txt` with the following function:

```
PowerGetActiveScheme
```

I see the following warning while running generate.py:

```
DEBUG: missing type 'Guid'
```

The function is then generated as:

```python
@winfunctype('POWRPROF.dll')
def PowerGetActiveScheme(UserRootPowerKey: HKEY, ActivePolicyGuid: POINTER(POINTER(MissingType))) -> WIN32_ERROR: ...
```

The second argument is a pointer to a pointer of type `MissingType` but should be a pointer to a pointer of a `Guid` struct as per [the docs](https://learn.microsoft.com/en-us/windows/win32/api/powersetting/nf-powersetting-powergetactivescheme).

Any idea why the GUID struct is not being generated correctly here?

Thanks
Fotis

**Comment by ynkdir** [comment]
Fixed.  Thank you for bug report.
