### ISSUE TITLE
How to generate mddbootstrap, __init__.py, _winrt.py, and xaml.py?

### ISSUE THREAD

**Issue by rileymjohnson** [ynkdir/py-win32more#40]
When I run the generator (command: `python -m win32generator`), it generates the `Microsoft` and `Windows` folders correctly, but it does not generated the `mddbootstrap` folder, `__init__.py`, `_winrt.py`, and `xaml.py`. How do I generate these files/folders?

**Comment by ynkdir** [comment]
Those files are written by hand.  Copy it to your generated folder manually.

**Comment by rileymjohnson** [comment]
Thanks
