### ISSUE TITLE
Add a NavigationViewItem Errpr

### ISSUE THREAD

**Issue by xiaoshuaiyo** [ynkdir/py-win32more#41]
I want to create a new NavigationViewItem, but it returns the following error
![21ff7628c1b2777f692eacf25836bed5](https://github.com/ynkdir/py-win32more/assets/139530289/a53ef1c4-ec9e-40cd-ac06-1b554b71d318)

This is my code
![82697ee9fc984f1e1248ceefef33877f](https://github.com/ynkdir/py-win32more/assets/139530289/e2fd7828-ab0d-42ae-8b7e-5e1530e32d73)

**Comment by xiaoshuaiyo** [comment]
I also have a question about how to customize the title bar while hiding the system title bar

**Comment by ynkdir** [comment]
Use PropertyValue.CreateString().

```python
from win32more.Windows.Foundation import PropertyValue

...

        nav_item1.Content = PropertyValue.CreateString("Test")
```

I expected that ctypes raise error in this situation.
I will add some type checks and conversion between IInspectable and str.

I'm not familiar with winui3 itself.

**Comment by xiaoshuaiyo** [comment]
> Use PropertyValue.CreateString().
> 
> ```python
> from win32more.Windows.Foundation import PropertyValue
> 
> ...
> 
>         nav_item1.Content = PropertyValue.CreateString("Test")
> ```
> 
> I expected that ctypes raise error in this situation. I will add some type checks and conversion between IInspectable and str.
> 
> I'm not familiar with winui3 itself.

Can the big guy see where my error is?
`Exception ignored on calling ctypes callback function: functools.partial(<bound method Vtbl._winrt_callback of 
<win32more._winrt.Vtbl object at 0x000002321770D040>>, <bound method XamlApplication._OnLaunched_wrapper of <App object at 0x00000232176D2F40>>, None)

Traceback (most recent call last):
  File "F:\Users\Happiness\Desktop\winui-python-main\winui-python-main\win32more\_winrt.py", line 681, in _winrt_callback
    r = callback(*args)
  File "F:\Users\Happiness\Desktop\winui-python-main\winui-python-main\win32more\xaml.py", line 85, in _OnLaunched_wrapper
    self._OnLaunched_wrapped(args)
  File "F:\Users\Happiness\Desktop\winui-python-main\winui-python-main\winui-xaml.py", line 100, in OnLaunched
    self._window = MainWindow()
  File "F:\Users\Happiness\Desktop\winui-python-main\winui-python-main\winui-xaml.py", line 28, in __new__
    self.InitializeComponent()
  File "F:\Users\Happiness\Desktop\winui-python-main\winui-python-main\winui-xaml.py", line 38, in InitializeComponent
    Application.LoadComponent(self, resource_locator)
  File "F:\Users\Happiness\Desktop\winui-python-main\winui-python-main\win32more\_winrt.py", line 462, in wrapper
    return getattr(factory, prototype.__name__)(*args, **kwargs)
  File "F:\Users\Happiness\Desktop\winui-python-main\winui-python-main\win32more\_winrt.py", line 232, in __call__
    return self._generic_delegate[generic_args](this, *args, **kwargs)
  File "F:\Users\Happiness\Desktop\winui-python-main\winui-python-main\win32more\_winrt.py", line 308, in __call__
    raise WinError(hr)
OSError: [WinError -2144665590] <no description>`
code:
`   from ctypes import addressof
    from pathlib import Path

    from win32more._winrt import Vtbl
    from win32more.Microsoft.UI.Xaml.Controls import Button
    from win32more.Windows.Foundation import IPropertyValue, PropertyValue, Uri
    from win32more.Windows.Win32.Foundation import S_OK
    from win32more.Windows.Win32.System.Com import IUnknown
    from win32more.Windows.Win32.System.WinRT import IInspectable
    from win32more.xaml import XamlApplication
    from win32more.Microsoft.UI.Xaml import Window, Application
    from win32more.Microsoft.UI.Xaml.Media import MicaBackdrop
    from win32more.Microsoft.UI.Xaml.Markup import IComponentConnector


    class MainWindow(Window):
        _keep_reference_in_python_world_ = {}

        # FIXME: implementing constructor using __new__() causes error in this case.
        def __new__(cls):
            self = super().__new__(cls, own=True)
            self._component_connector_vtbl = Vtbl(self, IComponentConnector)
            self.value = addressof(self._component_connector_vtbl)
            self._refcount = 0
            self.AddRef()
            self._inner = IInspectable()
            Window.CreateInstance(self, self._inner)
            self.InitializeComponent()
            return self
      
        def InitializeComponent(self):
            # ms-appx:///foo.xaml is relative to python.exe.
            # Use absolute path.
            # mx-appx:///C:/Full/Path/To/My.xaml
            # NOTE: According to documentation, LoadComponent() takes relative location.
            xaml_path = Path(__file__).with_name("winui-xaml.xaml").absolute().as_posix()
            resource_locator = Uri(f"ms-appx:///{xaml_path}")
            Application.LoadComponent(self, resource_locator)
      
        def QueryInterface(self, riid, ppvObject):
            if riid[0] == IUnknown._iid_:
                ppvObject[0] = addressof(self._component_connector_vtbl)
                self.AddRef()
                return S_OK
            elif riid[0] == IInspectable._iid_:
                ppvObject[0] = addressof(self._component_connector_vtbl)
                self.AddRef()
                return S_OK
            elif riid[0] == IComponentConnector._iid_:
                ppvObject[0] = addressof(self._component_connector_vtbl)
                self.AddRef()
                return S_OK
            else:
                return self._inner.QueryInterface(riid, ppvObject)
      
        def AddRef(self):
            self._refcount += 1
            if self._refcount == 1:
                self._keep_reference_in_python_world_[id(self)] = self
            return self._refcount
      
        def Release(self):
            self._refcount -= 1
            if self._refcount == 0:
                self._inner.Release()
                del self._keep_reference_in_python_world_[id(self)]
            return self._refcount
      
        def GetIids(self, iidCount, iids):
            return self._inner.GetIids(iidCount, iids)
      
        def GetRuntimeClassName(self, className):
            return self._inner.GetRuntimeClassName(className)
      
        def GetTrustLevel(self, trustLevel):
            return self._inner.GetTrustLevel(trustLevel)
      
        def Connect(self, connectionId, target):
            if connectionId == 1:
                self.Button1 = target.as_(Button)
                self.Button1.add_Click(self.Button1_OnClick)
            elif connectionId == 2:
                self.Button2 = target.as_(Button)
                self.Button2.add_Click(self.Button2_OnClick)
      
        def GetBindingConnector(self, connectionId, target):
            return None
      
        def Button1_OnClick(self, sender, e):
            text = self.Button1.Content.as_(IPropertyValue).GetString()
            self.Button1.Content = PropertyValue.CreateString(f"[{text}]")
      
        def Button2_OnClick(self, sender, e):
            text = self.Button2.Content.as_(IPropertyValue).GetString()
            self.Button2.Content = PropertyValue.CreateString(f"({text})")
      
      
      class App(XamlApplication):
        def OnLaunched(self, args):
            self._window = MainWindow()
            self._window.SystemBackdrop = MicaBackdrop.CreateInstance(None, None)
            self._window.ExtendsContentIntoTitleBar = True
            self._window.Activate()
      
      
      XamlApplication.Start(App)
`


XAML:
![74859ab12143702fa353520efc391a40](https://github.com/ynkdir/py-win32more/assets/139530289/3c2c18c8-8d94-4daa-9f96-87317851483d)

**Comment by ynkdir** [comment]
It works for me.

Error -2144665590 would be E_XAMLPARSEFAILED.
Your xaml file seems valid.
Is your xaml file saved in the same directory with your .py script with correct name??

**Comment by xiaoshuaiyo** [comment]
> 对我有用。
> 
> 错误-2144665590将是E_XAML语法分析失败。 您的xaml文件似乎有效。 你的xaml文件保存在同一个目录与你的.py脚本与正确的名称？？

Yes，it is.

**Comment by ynkdir** [comment]
I added scripts/debug.py.
Try `python scripts/debug.py /path/to/yourscript.py`.
You can see WinRT error message like `WinRT originate error - 0x802B000A : 'illegal qualified name character [Line: 10 Position: 5]'`.

**Comment by xiaoshuaiyo** [comment]
> 我添加了脚本/debug.py。 尝试。您可以看到 WinRT 错误消息，例如 。`python scripts/debug.py /path/to/yourscript.py``WinRT originate error - 0x802B000A : 'illegal qualified name character [Line: 10 Position: 5]'`

Can you make an example of a sidebar toggle page

**Comment by ynkdir** [comment]
Your code works.

[issue41.zip](https://github.com/user-attachments/files/15750645/issue41.zip)

**Comment by xiaoshuaiyo** [comment]
> 使用 PropertyValue.CreateString（）。
> 
> ```python
> from win32more.Windows.Foundation import PropertyValue
> 
> ...
> 
>         nav_item1.Content = PropertyValue.CreateString("Test")
> ```
> 
> 我预计在这种情况下 ctypes 会引发错误。我将在 IInspectable 和 str 之间添加一些类型检查和转换。
> 
> 我不熟悉 winui3 本身。

请问这个可以跨平台吗

**Comment by ynkdir** [comment]
> 请问这个可以跨平台吗
> google translate: Can this be cross-platform?

This library works on Windows only.
