### ISSUE TITLE
Structure construct confusing

### ISSUE THREAD

**Issue by shuffle2** [ynkdir/py-win32more#45]
The way which win32more abuses type hints on Structure-derived types seems to make it difficult to work with the library.

Example, say you want to make something like this:
```python
class SCSI_PASS_THROUGH_DIRECT_WITH_SENSE(Structure):
    sptd: Scsi.SCSI_PASS_THROUGH_DIRECT
    _pad: UInt32
    sense: Byte * 32
```

Using the structure is more difficult than if it were just expressed as a normal ctypes Structure, because you cannot use `ctypes.sizeof` on it, and you cannot easily initialize fields (nor rely on fields being zero initialized if not explicitly set).

i.e. with the above definition, you cannot do this:
```python
s = SCSI_PASS_THROUGH_DIRECT_WITH_SENSE()
s.sptd.Length = sizeof(s)
```
Attempting to access `.sptd.Length` will fail as `sptd` doesn't exist yet, and `sizeof` will fail for similar reason.

As a user of other win32 projections (cppwinrt + rust), I really like the projections when they are nicely integrated into the semantics of the language / interoperate well with existing code. win32more seems to be missing some of the glue code to make interworking nice.

**Comment by ynkdir** [comment]
I don't know that union problem.  Let me know detail.

**Comment by ynkdir** [comment]
I will give it a try.

**Comment by KubaO** [comment]
Note that commit is done automatically with lazy loading. So, if you want to implement your type in a module, at the end of the module just add `make_ready(__name__)`.
