### ISSUE TITLE
MLang is not included

### ISSUE THREAD

**Issue by moi15moi** [ynkdir/py-win32more#46]
I don't know if it is intended, win32more seems to miss all the Interfaces of [MLang](https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767865(v=vs.85)).

**Comment by ynkdir** [comment]
MLang apis are defined in Windows.Win32.Globalization namespace.

Windows.Win32.Globalization.IEnumCodePage
Windows.Win32.Globalization.IEnumRfc1766
Windows.Win32.Globalization.IEnumScript
Windows.Win32.Globalization.IMLangCodePages
Windows.Win32.Globalization.IMLangConvertCharset
Windows.Win32.Globalization.IMLangFontLink
Windows.Win32.Globalization.IMLangFontLink2
Windows.Win32.Globalization.IMLangLineBreakConsole
Windows.Win32.Globalization.IMLangString
Windows.Win32.Globalization.IMLangStringAStr
Windows.Win32.Globalization.IMLangStringWStr
Windows.Win32.Globalization.IMultiLanguage
Windows.Win32.Globalization.IMultiLanguage2
Windows.Win32.Globalization.IMultiLanguage3
Windows.Win32.Globalization.DetectEncodingInfo
Windows.Win32.Globalization.MIMECPINFO
Windows.Win32.Globalization.MIMECSETINFO
Windows.Win32.Globalization.RFC1766INFO
Windows.Win32.Globalization.SCRIPTFONTINFO
Windows.Win32.Globalization.SCRIPTINFO
Windows.Win32.Globalization.UNICODERANGE
Windows.Win32.Globalization.MIMECONTF
Windows.Win32.Globalization.MLCONVCHAR
Windows.Win32.Globalization.MLCP
Windows.Win32.Globalization.MLDETECTCP
Windows.Win32.Globalization.SCRIPTCONTF
Windows.Win32.Globalization.SCRIPTFONTCONTF

IMLangStringBuf is defined as

Windows.Win32.Globalization.IMLangStringBufA
Windows.Win32.Globalization.IMLangStringBufW


The followings are not defined in upstream win32metadata project.

IMLangStringNotifySink  (Doc says: Not implemented)
IMLStrAttr  (Doc says: Not implemented)
IMLStrAttrAStr  (Doc says: Not implemented)
IMLStrAttrLocale  (Doc says: Not implemented)
IMLStrAttrLong  (Doc says: Not implemented)
IMLStrAttrNotifySink  (Doc says: Not implemented)
IMLStrAttrWStr  (Doc says: Not implemented)

ConvertINetMultiByteToUnicode   (define in mlang.h)
ConvertINetString   (define in mlang.h)
ConvertINetUnicodeToMultiByte   (define in mlang.h)
IsConvertINetStringAvailable   (define in mlang.h)
LcidToRfc1766   (define in mlang.h)
Rfc1766ToLcid   (define in mlang.h)

**Comment by moi15moi** [comment]
Wow, ok. The github search it broken ^^'
See https://github.com/search?q=repo%3Aynkdir%2Fpy-win32more%20IEnumScript&type=code
