### ISSUE TITLE
Is there any documentations here?

### ISSUE THREAD

**Issue by mstouk57g** [ynkdir/py-win32more#47]

**Comment by ynkdir** [comment]
No, there isn't.

**Comment by mstouk57g** [comment]
Ah?!
So , could you please tell me how I can use this module…
For example , something to read?

**Comment by mstouk57g** [comment]
Or could you please give few documentations? (maybe impossible? )…….

**Comment by ynkdir** [comment]
See readme and example directory.

This library is just a pre-defined Windows API types and functions for ctypes.
[Windows API reference](https://learn.microsoft.com/en-us/windows/win32/) and [Python's ctypes reference](https://docs.python.org/3/library/ctypes.html) are useful.
Most Apis are defined as documented without changing signature.

I am not English speaker.
I can not write documentation.

**Comment by mstouk57g** [comment]
Thanks you a lot. I’ll continue exploring and developing.
( By the way, I’m not an English speaker either. )

**Comment by jhi2** [comment]
Use the reference at [https://learn.microsoft.com/en-us/windows/win32/api/](https://learn.microsoft.com/en-us/windows/win32/api/). Then just pythonize the C++ code.
