### ISSUE TITLE
Any plans to support Cygwin?

### ISSUE THREAD

**Issue by moi15moi** [ynkdir/py-win32more#51]
Currently, win32more cannot be used with cygwin since this package use some windows only ctypes function.
Here is a example of an exception when I try to import win32more on cygwin.
```py
Traceback (most recent call last):
  File "/cygdrive/c/Users/jerem/Downloads/test.py", line 6, in <module>
    from win32more import FAILED, Guid, Int32
  File "/usr/local/lib/python3.9/site-packages/win32more/__init__.py", line 5, in <module>
    from ctypes import (
ImportError: cannot import name 'WINFUNCTYPE' from 'ctypes' (/usr/lib/python3.9/ctypes/__init__.py)
```

Is there any plan to support cygwin?

**Comment by ynkdir** [comment]
Not planned unless ctypes supports WINFUNCTYPE in cygwin.
WINFUNCTYPE is required to call Windows API.

**Comment by ynkdir** [comment]
It seems that 64bit Windows uses same calling convention for both C function and Api function.
So, CFUNCTYPE may work for win32 api.
I will add workaround for cygwin.

**Comment by moi15moi** [comment]
I think you forgot to push the file ``_cygwin.py``.
It isn't [available](https://github.com/ynkdir/py-win32more/blob/main/win32more/_cygwin.py), but you try to import it [here](https://github.com/ynkdir/py-win32more/blob/c444fbeb45ee4c6a718010504424b73add811043/win32more/__init__.py#L50)

**Comment by ynkdir** [comment]
I added.  Thank you.
