### ISSUE TITLE
Can these tools be used to call a new API/winmd from python?

### ISSUE THREAD

**Issue by TheRealColeB** [ynkdir/py-win32more#52]
I have a C API that I would like to project to other languages, including python.  I can use tools in the win32metadata project to create a WinMD file describing my API.  Can the tools in the py-win32more project be used to call my API in python?

I am following the pattern in 

https://withinrafael.com/2023/01/18/generating-metadata-for-the-windows-crate

but I am trying to do the same thing in python in addition to Rust.

Thank you,

Cole

**Comment by ynkdir** [comment]
Maybe it is possible.

First, you need to convert your winmd to json using [winmd-printer](https://github.com/ynkdir/winmd-printer).

```
git clone https://github.com/ynkdir/winmd-printer.git
cd winmd-printer
dotnet run -o YourMetadata.json YourMetadata.winmd
```

Then, pass it to win32generator.

```
cd /path/to/py-win32more
py -m win32generator .\win32generator\resources\metadata\Windows.Win32.json.xz .\win32generator\resources\metadata\WindowsSDK.json.xz YourMetadata.json
```

You might want to edit result because apis are generated under win32more namespace.
