### ISSUE TITLE
Can I use custom title bar？

### ISSUE THREAD

**Issue by xiaoshuaiyo** [ynkdir/py-win32more#53]
I'm trying to hide the system title bar with a custom title bar, but he doesn't seem to work
![a91234c6857d075dea6e4521b31b30fe](https://github.com/user-attachments/assets/9cfc092f-10eb-4217-b2a4-d45d4dd105e4)
![2ef62cf331abe272cb839876e80a3e60](https://github.com/user-attachments/assets/27fd84fb-582e-47bf-94ac-83485c4ccf64)
![5c41b896cb2150ca8b0aa6863260fb09](https://github.com/user-attachments/assets/c289c544-8563-47d7-ac38-ec4ec717d15e)

**Comment by xiaoshuaiyo** [comment]
And can you also teach me how to create a login Dialog? Thank you so much！

**Comment by xiaoshuaiyo** [comment]
> And can you also teach me how to create a login Dialog? Thank you so much！

Also, I want this dialog box to automatically pop up when the application starts, and only after entering the correct content can the application be launched

**Comment by ynkdir** [comment]
Please paste whole your code as text instead of image so that I can reproduce it.

It seems that XamlReader.Load() fails.  It means that xaml is invalid.

Try `py scripts/debug.py yourcode.py` and paste result.

**Comment by xiaoshuaiyo** [comment]
> Please paste whole your code as text instead of image so that I can reproduce it.
> 
> It seems that XamlReader.Load() fails. It means that xaml is invalid.
> 
> Try `py scripts/debug.py yourcode.py` and paste result.

You can close issues.
