### ISSUE TITLE
Latest Windows App SDK,older releases

### ISSUE THREAD

**Issue by monkeycc** [ynkdir/py-win32more#59]
![xx](https://github.com/user-attachments/assets/40c37e8f-63c5-4860-9596-e31a71b023d3)

```
# TODO: keep sync with WindowsAppSDK-VersionInfo.h
# VERSION: 1.5.240428000
WINDOWSAPPSDK_RELEASE_MAJORMINOR = 0x00010005

win32more\mddbootstrap\__init__.py
```

**Comment by ynkdir** [comment]
WindowsAppSDK was updated to 1.6 in a latest source code.
I will release new version in a few days.

**Comment by ynkdir** [comment]
New version was released.
