### ISSUE TITLE
Automatically update the code with win32generator

### ISSUE THREAD

**Issue by moi15moi** [ynkdir/py-win32more#63]
I think it would be a plus if there would be a workflow that update the code when there is a new Windows API. It could automatically push the change in the main branch or open a PR.

I would want to do it, but I have some question.
From what I can see, ``win32generator`` does this jobs and it depends on the files in [metadata](https://github.com/ynkdir/py-win32more/tree/main/win32generator/resources/metadata).

Where do get those file?
``Windows.Win32.json.xz`` from [Microsoft.Windows.SDK.Win32Metadata](https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Metadata)?
``WindowsAppSDK.json.xz`` from [Microsoft.WindowsAppSDK](https://www.nuget.org/packages/Microsoft.WindowsAppSDK)?
``WindowsSDK.json.xz`` from [Microsoft.Windows.SDK.NET.Ref](https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref)?
The ``.nupkg`` file doesn't seems to contain the json that you have.

**Comment by ynkdir** [comment]
WindowsSDK is from https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts
WebView2 is from https://www.nuget.org/packages/Microsoft.Web.WebView2
(WebView2 is merged into WindowsAppSDK for now)

.winmd files in .nupkg are converted to json with https://github.com/ynkdir/winmd-printer

winmd-printer has script to download and convert.
For example to get win32metadata: `./scripts/get_win32.ps1 v63.0.31`.
You need .NET SDK to run it.
